name: Generate Descriptive Wiki

on:
  push:
    branches:
      - main

jobs:
  generate-wiki:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install openai --upgrade
        # pip install -r requirements.txt  # Replace with your requirements file path
        
    - name: Run Script to Generate Wiki
      env:
          API_KEY: ${{ secrets.azureOpenAI_key }}
          API_ENDPOINT: ${{ secrets.azureOpenAI_endpoint }}
      run: |
        python generate_wiki.py

    - name: Commit and Push Markdown Output
      run: |
        git config --global user.email "actions@github.com"
        git config --global user.name "GitHub Actions"
        git add .
        git commit -m "Update descriptive wiki"
        git push
        
    - name: Deploy Docusaurus to gh-pages
      run: |
       cd api-wiki
       npm install
       npm run build
       echo "GIT_USER=vipray-ms" >> $GITHUB_ENV
       npm run deploy
