name: Generate Descriptive Wiki

on:
  push:
    branches:
      - main

jobs:
  generate-wiki:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Run Script to Generate Wiki
      run: |
        python generate_wiki.py

    - name: Commit and Push Markdown Output
      run: |
        git config --global user.email "actions@github.com"
        git config --global user.name "GitHub Actions"
        git add descriptive_wiki.md
        git commit -m "Update descriptive wiki"
        git push
